name: Build Opusfile on Windows (MSYS2)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          base-devel
          git
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-libogg
          mingw-w64-x86_64-opus
          mingw-w64-x86_64-openssl

    - name: Build opusfile
      shell: msys2 {0}
      run: |
        autoreconf -i
        ./configure --prefix=/mingw64
        make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: opusfile-binaries
        path: |
          .libs/*.dll
          .libs/*.a
          .libs/*.la
          .libs/*.lib